export const UPDATE_GAME_MODE = 'UPDATE_GAME_MODE';
export const UPDATE_ROWS = 'UPDATE_ROWS';
export const UPDATE_COLUMNS = 'UPDATE_COLUMNS';
export const UPDATE_COLORS = 'UPDATE_COLORS';
export const UPDATE_BALL_SIZE = 'UPDATE_BALL_SIZE';
export const UPDATE_ALL_PARAMS = 'UPDATE_ALL_PARAMS';
