export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_LANG = 'TOGGLE_LANG';
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const UPDATE_ANIMATE = 'UPDATE_ANIMATE';
